import json
import copy

def create_code_cell(source_lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [line + "\n" if not line.endswith("\n") else line for line in source_lines]
    }

def create_markdown_cell(source_lines):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [line + "\n" if not line.endswith("\n") else line for line in source_lines]
    }

nb_path = "kombinasi_5.ipynb"
with open(nb_path, "r") as f:
    nb = json.load(f)

# The large cell is at index 3 (0-based) based on the previous view
# Check just to be sure
cells = nb["cells"]
large_cell = cells[4] # It was index 4 in the file view (line 127 starts cell 3, wait. Line 65 is cell 2 (markdown). Line 21 is cell 1 (code). Line 3 is cell 0 (markdown).
# Let's count properly from the file view:
# Cell 0: Markdown (Title)
# Cell 1: Code (Setup & Imports)
# Cell 2: Markdown (Tahap 1)
# Cell 3: Code (Data Acquisition) -> Execution count 2
# Cell 4: Code (Helper Functions) -> The one we want to split. Execution count 3.

target_cell_index = 4
original_source = "".join(cells[target_cell_index]["source"])

# Define the code blocks
block1_imports_game_theory = [
    "# === 1. Game Theory & Payoff Matrix Functions ===\n",
    "import pennylane as qml\n",
    "from scipy import linalg as la\n",
    "from itertools import combinations\n",
    "import numpy as np\n",
    "\n",
    "def compute_endogenous_lambda(log_returns, tickers):\n",
    "    \"\"\"λ_market = σ_avg / (μ_avg + σ_avg), annualized\"\"\"\n",
    "    mean_ret = log_returns[tickers].mean() * 252\n",
    "    std_dev = log_returns[tickers].std() * np.sqrt(252)\n",
    "    mu_avg = abs(mean_ret).mean()\n",
    "    sigma_avg = std_dev.mean()\n",
    "    if np.isnan(mu_avg) or np.isnan(sigma_avg) or (mu_avg + sigma_avg) == 0:\n",
    "        return 0.5\n",
    "    return sigma_avg / (mu_avg + sigma_avg)\n",
    "\n",
    "def compute_markowitz_payoff_matrix(log_returns, binary_states, asset_a, asset_b, lambda_risk):\n",
    "    \"\"\"Calculate Markowitz payoff matrix 2x2 for a pair of assets.\"\"\"\n",
    "    state_A = binary_states[asset_a].values\n",
    "    state_B = binary_states[asset_b].values\n",
    "    ret_A = log_returns[asset_a].values\n",
    "    ret_B = log_returns[asset_b].values\n",
    "    \n",
    "    payoff_A = np.zeros((2, 2))\n",
    "    payoff_B = np.zeros((2, 2))\n",
    "    counts = np.zeros((2, 2))\n",
    "    \n",
    "    for t in range(len(state_A)):\n",
    "        i, j = int(state_A[t]), int(state_B[t])\n",
    "        counts[i, j] += 1\n",
    "        # Utility: (1-λ)µ - λσ\n",
    "        u_A = (1 - lambda_risk) * (ret_A[t] * 252) - lambda_risk * abs(ret_A[t] * 252)\n",
    "        u_B = (1 - lambda_risk) * (ret_B[t] * 252) - lambda_risk * abs(ret_B[t] * 252)\n",
    "        payoff_A[i, j] += u_A\n",
    "        payoff_B[i, j] += u_B\n",
    "    \n",
    "    # Average\n",
    "    for i in range(2):\n",
    "        for j in range(2):\n",
    "            if counts[i, j] > 0:\n",
    "                payoff_A[i, j] /= counts[i, j]\n",
    "                payoff_B[i, j] /= counts[i, j]\n",
    "    return payoff_A, payoff_B\n",
    "\n",
    "def classify_game_type(payoff_A, payoff_B):\n",
    "    \"\"\"Classify game type based on payoff structure.\"\"\"\n",
    "    coord_A = (payoff_A[0, 0] > payoff_A[1, 0]) and (payoff_A[1, 1] > payoff_A[0, 1])\n",
    "    coord_B = (payoff_B[0, 0] > payoff_B[0, 1]) and (payoff_B[1, 1] > payoff_B[1, 0])\n",
    "    \n",
    "    if coord_A and coord_B:\n",
    "        return \"Coordination Game\"\n",
    "    elif (not coord_A) and (not coord_B):\n",
    "        return \"Anti-Coordination Game\"\n",
    "    else:\n",
    "        return \"Mixed Strategy Game\"\n"
]

block2_demo_game_theory = [
    "# === DEMO: Game Theory Analysis ===\n",
    "# Calculate λ and Payoff Matrices for the full dataset as an example\n",
    "\n",
    "print(\"--- Game Theory Analysis (Full Period) ---\")\n",
    "lam_demo = compute_endogenous_lambda(log_returns, tickers)\n",
    "print(f\"Endogenous Lambda (λ): {lam_demo:.4f}\")\n",
    "\n",
    "pairs = list(combinations(range(len(tickers)), 2))\n",
    "for idx_a, idx_b in pairs:\n",
    "    a, b = tickers[idx_a], tickers[idx_b]\n",
    "    pA, pB = compute_markowitz_payoff_matrix(log_returns, binary_states, a, b, lam_demo)\n",
    "    gtype = classify_game_type(pA, pB)\n",
    "    print(f\"\\nPair {a} vs {b}:\")\n",
    "    print(f\"  Game Type: {gtype}\")\n",
    "    print(f\"  Payoff A:\\n{pA}\")\n",
    "    print(f\"  Payoff B:\\n{pB}\")"
]

block3_hamiltonian_funcs = [
    "# === 2. Hamiltonian & Quantum Mutual Information ===\n",
    "\n",
    "def compute_bias_hi(all_payoffs, tickers):\n",
    "    \"\"\"Calculate bias h_i from marginal payoff matrices.\"\"\"\n",
    "    n_assets = len(tickers)\n",
    "    h = np.zeros(n_assets)\n",
    "    for i in range(n_assets):\n",
    "        payoff_sum = 0\n",
    "        count = 0\n",
    "        for (a, b), (pA, pB) in all_payoffs.items():\n",
    "            if a == i:\n",
    "                # Difference between state 1 and 0\n",
    "                payoff_sum += (pA[1, 0] + pA[1, 1]) - (pA[0, 0] + pA[0, 1])\n",
    "                count += 1\n",
    "            elif b == i:\n",
    "                payoff_sum += (pB[0, 1] + pB[1, 1]) - (pB[0, 0] + pB[1, 0])\n",
    "                count += 1\n",
    "        if count > 0:\n",
    "            h[i] = payoff_sum / count\n",
    "    return h\n",
    "\n",
    "def compute_qmi_jij(binary_states, asset_a, asset_b, alpha=1.0):\n",
    "    \"\"\"Calculate Quantum Mutual Information (QMI) as J_ij.\"\"\"\n",
    "    state_A = binary_states[asset_a].values\n",
    "    state_B = binary_states[asset_b].values\n",
    "    N = len(state_A)\n",
    "    \n",
    "    n_ij = np.zeros((2, 2))\n",
    "    for t in range(N):\n",
    "        n_ij[int(state_A[t]), int(state_B[t])] += 1\n",
    "    prob_joint = (n_ij + alpha) / (N + 4 * alpha)\n",
    "    \n",
    "    rho_LF = np.diag(prob_joint.flatten())\n",
    "    rho_L = np.diag(prob_joint.sum(axis=1))\n",
    "    rho_F = np.diag(prob_joint.sum(axis=0))\n",
    "    \n",
    "    def von_neumann_entropy(rho):\n",
    "        eigenvalues = np.real(la.eigvalsh(rho))\n",
    "        eigenvalues = eigenvalues[eigenvalues > 1e-12]\n",
    "        return -np.sum(eigenvalues * np.log(eigenvalues))\n",
    "    \n",
    "    S_LF = von_neumann_entropy(rho_LF)\n",
    "    S_L = von_neumann_entropy(rho_L)\n",
    "    S_F = von_neumann_entropy(rho_F)\n",
    "    return S_L + S_F - S_LF\n",
    "\n",
    "def build_hamiltonian(h, J, n_assets, K=2, penalty_A=10.0):\n",
    "    \"\"\"Build total Hamiltonian = H_cost + H_constraint\"\"\"\n",
    "    coeffs = []\n",
    "    obs = []\n",
    "    \n",
    "    # H_cost terms\n",
    "    for i in range(n_assets):\n",
    "        if abs(h[i]) > 1e-10:\n",
    "            coeffs.append(float(h[i]))\n",
    "            obs.append(qml.PauliZ(i))\n",
    "    \n",
    "    for i in range(n_assets):\n",
    "        for j in range(i + 1, n_assets):\n",
    "            if abs(J[i, j]) > 1e-10:\n",
    "                coeffs.append(float(J[i, j]))\n",
    "                obs.append(qml.PauliZ(i) @ qml.PauliZ(j))\n",
    "    \n",
    "    # H_constraint terms\n",
    "    N_half_minus_K = n_assets / 2.0 - K\n",
    "    const_val = penalty_A * (N_half_minus_K**2 + n_assets / 4.0)\n",
    "    coeffs.append(float(const_val))\n",
    "    obs.append(qml.Identity(0))\n",
    "    \n",
    "    for i in range(n_assets):\n",
    "        coeff = -penalty_A * N_half_minus_K\n",
    "        coeffs.append(float(coeff))\n",
    "        obs.append(qml.PauliZ(i))\n",
    "    \n",
    "    for i in range(n_assets):\n",
    "        for j in range(i + 1, n_assets):\n",
    "            coeffs.append(float(penalty_A * 0.5))\n",
    "            obs.append(qml.PauliZ(i) @ qml.PauliZ(j))\n",
    "    \n",
    "    return qml.Hamiltonian(coeffs, obs)\n"
]

block4_demo_hamiltonian = [
    "# === DEMO: Hamiltonian Construction ===\n",
    "print(\"--- Hamiltonian Parameters (Full Period) ---\")\n",
    "\n",
    "# Re-calculate Payoffs for h calculation\n",
    "all_payoffs_demo = {}\n",
    "for idx_a, idx_b in pairs:\n",
    "    a, b = tickers[idx_a], tickers[idx_b]\n",
    "    pA, pB = compute_markowitz_payoff_matrix(log_returns, binary_states, a, b, lam_demo)\n",
    "    all_payoffs_demo[(idx_a, idx_b)] = (pA, pB)\n",
    "\n",
    "h_demo = compute_bias_hi(all_payoffs_demo, tickers)\n",
    "print(f\"Bias fields (h): {h_demo}\")\n",
    "\n",
    "J_demo = np.zeros((len(tickers), len(tickers)))\n",
    "print(\"\\nCouplings (J_ij based on QMI):\")\n",
    "for i in range(len(tickers)):\n",
    "    for j in range(i + 1, len(tickers)):\n",
    "        qmi = compute_qmi_jij(binary_states, tickers[i], tickers[j])\n",
    "        J_demo[i, j] = qmi\n",
    "        J_demo[j, i] = qmi\n",
    "        print(f\"  {tickers[i]} - {tickers[j]}: {qmi:.6f}\")\n",
    "\n",
    "H_demo = build_hamiltonian(h_demo, J_demo, n_assets=len(tickers), K=2)\n",
    "print(f\"\\nHamiltonian Terms: {len(H_demo.ops)}\")\n",
    "print(\"Example Term 0:\", H_demo.ops[0], \"Coeff:\", H_demo.coeffs[0])"
]

block5_vqe = [
    "# === 3. VQE Solver (SPSA) ===\n",
    "\n",
    "def solve_vqe(H, n_qubits, K=2, depth=2, maxiter=100, n_shots=4096, seed=42):\n",
    "    \"\"\"Run VQE using SPSA optimizer and probabilistic sampling.\"\"\"\n",
    "    dev = qml.device(\"default.qubit\", wires=n_qubits) # Analytic for optimization\n",
    "    \n",
    "    @qml.qnode(dev)\n",
    "    def cost_circuit(params):\n",
    "        weights = params.reshape((depth + 1, n_qubits, 2))\n",
    "        for layer in range(depth + 1):\n",
    "            for q in range(n_qubits):\n",
    "                qml.RY(weights[layer, q, 0], wires=q)\n",
    "                qml.RZ(weights[layer, q, 1], wires=q)\n",
    "            if layer < depth:\n",
    "                for q in range(n_qubits):\n",
    "                    qml.CNOT(wires=[q, (q + 1) % n_qubits])\n",
    "        return qml.expval(H)\n",
    "\n",
    "    rng = np.random.default_rng(seed)\n",
    "    n_params = n_qubits * 2 * (depth + 1)\n",
    "    params = rng.uniform(0, 2 * np.pi, n_params)\n",
    "    \n",
    "    # SPSA Configuration\n",
    "    initial_cost = float(cost_circuit(params))\n",
    "    a = 0.1 * max(1.0, abs(initial_cost))\n",
    "    c = 0.10\n",
    "    A = maxiter * 0.1\n",
    "    alpha = 0.602\n",
    "    gamma = 0.101\n",
    "    \n",
    "    for k in range(maxiter):\n",
    "        a_k = a / (A + k + 1) ** alpha\n",
    "        c_k = c / (k + 1) ** gamma\n",
    "        delta = 2 * rng.integers(0, 2, size=n_params) - 1\n",
    "        \n",
    "        cost_plus = float(cost_circuit(params + c_k * delta))\n",
    "        cost_minus = float(cost_circuit(params - c_k * delta))\n",
    "        grad = (cost_plus - cost_minus) / (2 * c_k * delta)\n",
    "        params = params - a_k * grad\n",
    "\n",
    "    # Sampling Selection\n",
    "    dev_sample = qml.device(\"default.qubit\", wires=n_qubits, shots=n_shots)\n",
    "    @qml.qnode(dev_sample)\n",
    "    def sample_circuit(params):\n",
    "        weights = params.reshape((depth + 1, n_qubits, 2))\n",
    "        for layer in range(depth + 1):\n",
    "            for q in range(n_qubits):\n",
    "                qml.RY(weights[layer, q, 0], wires=q)\n",
    "                qml.RZ(weights[layer, q, 1], wires=q)\n",
    "            if layer < depth:\n",
    "                for q in range(n_qubits):\n",
    "                    qml.CNOT(wires=[q, (q + 1) % n_qubits])\n",
    "        return qml.probs(wires=range(n_qubits))\n",
    "\n",
    "    probs = sample_circuit(params)\n",
    "    \n",
    "    # Filter for Hamming weight K\n",
    "    best_bitstring = None\n",
    "    best_prob = -1.0\n",
    "    for i, p in enumerate(probs):\n",
    "        bs = format(i, f'0{n_qubits}b')\n",
    "        if bs.count('1') == K:\n",
    "            if p > best_prob:\n",
    "                best_prob = p\n",
    "                best_bitstring = bs\n",
    "                \n",
    "    # Fallback\n",
    "    if best_bitstring is None:\n",
    "        sorted_indices = np.argsort(probs)[::-1]\n",
    "        for idx in sorted_indices:\n",
    "             bs = format(idx, f'0{n_qubits}b')\n",
    "             if bs.count('1') == K:\n",
    "                 best_bitstring = bs\n",
    "                 break\n",
    "        if best_bitstring is None:\n",
    "             best_bitstring = \"0\" * (n_qubits - K) + \"1\" * K\n",
    "\n",
    "    selected_indices = [i for i, bit in enumerate(best_bitstring) if bit == '1']\n",
    "    return selected_indices"
]

block6_strategy_step = [
    "# === 4. Strategy Orchestration ===\n",
    "\n",
    "def run_strategy_step(lookback_data, tickers, K=2, penalty_A=10.0):\n",
    "    \"\"\"Run full strategy pipeline for a single step.\"\"\"\n",
    "    # 1. Preprocessing\n",
    "    log_rets = np.log(lookback_data / lookback_data.shift(1)).dropna()\n",
    "    binary_sts = (log_rets <= 0).astype(int)\n",
    "    \n",
    "    # 2. Parameters\n",
    "    lam = compute_endogenous_lambda(log_rets, tickers)\n",
    "    \n",
    "    # 3. Payoffs & Market Phase\n",
    "    all_payoffs = {}\n",
    "    game_counts = {\"Coordination\": 0, \"Anti-Coordination\": 0, \"Mixed\": 0}\n",
    "    \n",
    "    pairs = list(combinations(range(len(tickers)), 2))\n",
    "    for idx_a, idx_b in pairs:\n",
    "        a, b = tickers[idx_a], tickers[idx_b]\n",
    "        pA, pB = compute_markowitz_payoff_matrix(log_rets, binary_sts, a, b, lam)\n",
    "        all_payoffs[(idx_a, idx_b)] = (pA, pB)\n",
    "        gtype = classify_game_type(pA, pB)\n",
    "        if \"Coordination\" in gtype and \"Anti\" not in gtype:\n",
    "            game_counts[\"Coordination\"] += 1\n",
    "        elif \"Anti-Coordination\" in gtype:\n",
    "            game_counts[\"Anti-Coordination\"] += 1\n",
    "        else:\n",
    "            game_counts[\"Mixed\"] += 1\n",
    "            \n",
    "    dominant = max(game_counts, key=game_counts.get)\n",
    "    print(f\"  [{lookback_data.index[-1].strftime('%Y-%m-%d')}] Phase: {dominant} (λ={lam:.4f})\")\n",
    "        \n",
    "    h = compute_bias_hi(all_payoffs, tickers)\n",
    "    \n",
    "    # 4. QMI\n",
    "    J = np.zeros((len(tickers), len(tickers)))\n",
    "    for i in range(len(tickers)):\n",
    "        for j in range(i + 1, len(tickers)):\n",
    "            qmi = compute_qmi_jij(binary_sts, tickers[i], tickers[j])\n",
    "            J[i, j] = qmi\n",
    "            J[j, i] = qmi\n",
    "            \n",
    "    # 5. VQE\n",
    "    H = build_hamiltonian(h, J, n_assets=len(tickers), K=K, penalty_A=penalty_A)\n",
    "    selected_indices = solve_vqe(H, n_qubits=len(tickers), K=K, maxiter=100)\n",
    "    \n",
    "    return selected_indices"
]

# Create new cells
new_cells = [
    create_markdown_cell(["## 2. Helper Functions & Demo Output"]),
    create_code_cell(block1_imports_game_theory),
    create_code_cell(block2_demo_game_theory),
    create_code_cell(block3_hamiltonian_funcs),
    create_code_cell(block4_demo_hamiltonian),
    create_code_cell(block5_vqe),
    create_code_cell(block6_strategy_step)
]

# Insert new cells in place of the old large cell
nb["cells"] = cells[:target_cell_index] + new_cells + cells[target_cell_index+1:]

with open("kombinasi_5.ipynb", "w") as f:
    json.dump(nb, f, indent=1)

print("Notebook split successfully.")
