import re

files = {
    'Contents/3_Metodologi/Bab-3.1.tex': """
Penelitian ini diawali dengan merumuskan alur metodologi yang komprehensif untuk memecahkan masalah optimasi portofolio biner menggunakan pendekatan hibrida kuantum. Struktur metodologis ini dipetakan secara sistematis untuk menghubungkan tahap ekstraksi data finansial historis dengan perumusan model Hamiltonian Ising yang merepresentasikan lanskap energi sistem. Lanskap energi tersebut selanjutnya dikalibrasi menggunakan prinsip \\textit{Exact Potential Game} guna menemukan titik ekuilibrium strategis sebelum diproses secara intensif oleh perangkat keras kuantum. Titik ekuilibrium strategis ini bertindak sebagai basis inisialisasi awal bagi algoritma \\textit{Hardware-Efficient Variational Quantum Eigensolver} (HE-VQE) dalam menemukan konfigurasi portofolio dengan energi paling minimum. Keseluruhan alur kerja komputasi kuantum tersebut kemudian dievaluasi menggunakan simulasi \\textit{backtesting} berkelanjutan untuk mengukur ketahanan strategi investasi pada kondisi pasar riil yang sangat dinamis.

Diagram alir metodologi yang divisualisasikan pada Gambar \\ref{fig:flowchart_gt_vqe} menjabarkan keterkaitan fungsional antar setiap modul komputasi secara sekuensial dari awal hingga evaluasi akhir. Modul pra-pemrosesan data klasik berperan krusial dalam menghasilkan parameter fundamental seperti vektor imbal hasil dan matriks kovariansi yang mutlak dibutuhkan untuk membentuk operator kuantum. Proses optimasi kuantum yang divisualisasikan secara eksplisit mencakup siklus iteratif penyesuaian sudut gerbang rotasi kuantum serta mekanisme adaptasi kedalaman sirkuit secara bertahap sesuai kebutuhan. Parameter pinalti dinamis turut diintegrasikan ke dalam rangkaian siklus optimasi untuk membatasi ruang pencarian sehingga konfigurasi portofolio yang dihasilkan selalu terjamin memenuhi kendala kardinalitas. Keterpaduan struktural antara ekstraksi parameter klasik, inisialisasi teori permainan, dan optimasi kuantum adaptif ini dikonstruksi secara logis untuk menjamin keandalan operasional metodologi secara keseluruhan.
""",
    'Contents/3_Metodologi/Bab-3.2.tex': """
Prosedur akuisisi data finansial dirancang untuk memperoleh representasi harga penutupan aset secara historis yang kemudian dikonversi menjadi logaritma imbal hasil. Transformasi logaritmik ini diberlakukan secara ketat untuk menstabilkan distribusi statistik data sekaligus memfasilitasi komputasi matriks kovariansi yang merepresentasikan risiko sistemik antar aset. Parameter penghindaran risiko atau \\textit{risk aversion} diekstraksi secara otomatis menggunakan skor-Z agregat yang mencerminkan tingkat volatilitas serta ekspektasi keuntungan pasar pada jendela observasi tertentu. Metode parameterisasi endogen ini diterapkan untuk memastikan bahwa model Hamiltonian yang terbentuk memiliki fleksibilitas tinggi dalam merespons fluktuasi ekstrem pada lingkungan pasar riil. Logika pemrosesan tahap awal ini menjadi fondasi kuantitatif yang mengarahkan pembentukan lanskap energi untuk tahapan komputasi kuantum selanjutnya.

Rangkaian prosedur pra-pemrosesan data beserta ekstraksi metrik statistika tersebut dikodifikasikan secara terstruktur ke dalam Algoritma \\ref{alg:data_prep} untuk memudahkan eksekusi komputasi. Algoritma ini menerima input berupa daftar simbol aset serta batasan periode waktu untuk menghasilkan matriks kovariansi, vektor imbal hasil, dan nilai penghindaran risiko. Modul pembersihan data terintegrasi di dalam prosedur algoritma untuk menghilangkan nilai kosong atau anomali yang berpotensi merusak integritas matriks kovariansi dan operator kuantum. Penggunaan formula sigmoid pada perhitungan variabel penghindaran risiko memberikan batas atas dan batas bawah yang terukur sehingga koefisien pinalti tidak mendominasi fungsi objektif utama. Konfigurasi numerik yang dihasilkan oleh algoritma awal ini langsung didistribusikan ke dalam modul konstruksi Hamiltonian untuk dipetakan menjadi arsitektur sirkuit kuantum yang setara.
""",
    'Contents/3_Metodologi/Bab-3.3.tex': """
Transformasi masalah optimasi portofolio menjadi kerangka kerja \\textit{Quadratic Unconstrained Binary Optimization} (QUBO) diwajibkan untuk merepresentasikan objektif minimalisasi risiko dan maksimalisasi imbal hasil finansial. Formulasi kuadratik ini mengintegrasikan fungsi pinalti linier yang berfungsi secara eksplisit untuk menjamin bahwa portofolio kuantum selalu memilih kombinasi aset sesuai batasan kardinalitas yang diinginkan. Variabel keputusan biner dalam matriks QUBO selanjutnya dipetakan secara matematis ke dalam variabel \\textit{spin} fisis untuk membentuk model Hamiltonian Ising yang ekuivalen. Pemetaan ini menghasilkan vektor bias tunggal serta matriks interaksi ganda yang mencerminkan struktur kopling antar \\textit{qubit} dalam arsitektur perangkat keras kuantum. Modifikasi topologi masalah ini mensyaratkan presisi numerik yang tinggi karena setiap kesalahan pemetaan akan mengubah ekuilibrium lanskap energi secara drastis pada komputasi akhir.

Prosedur transformasi QUBO menuju representasi operator Pauli disajikan secara algoritmik melalui tahapan komputasi berurutan yang diformalkan pada Algoritma \\ref{alg:hamiltonian_construction}. Algoritma tersebut secara eksplisit menerima input matriks statistik finansial klasik untuk kemudian mengonstruksi nilai diagonal serta elemen luar diagonal dari matriks kuadratik bobot pinalti. Transformasi variabel Ising diaplikasikan secara langsung pada baris-baris algoritma untuk mendeduksi koefisien kopling magnetik dan nilai bias lokal yang akan disuntikkan ke dalam gerbang rotasi kuantum. Penjumlahan matematis dari seluruh konstanta pergeseran energi juga dicatat dengan saksama guna memastikan bahwa nilai ekspektasi dari sirkuit dapat diterjemahkan kembali ke utilitas finansial yang sebenarnya. Rangkaian instruksi komputasi ini memastikan bahwa operator Hamiltonian yang dihasilkan sepenuhnya kompatibel untuk dieksekusi oleh penyelesai variasional pada tahap simulasi berikutnya.
""",
    'Contents/3_Metodologi/Bab-3.4.tex': """
Interaksi strategis antar instrumen finansial dimodelkan secara matematis sebagai sebuah \\textit{Exact Potential Game} untuk mengekstraksi informasi mengenai konfigurasi aset yang paling rasional secara ekonomi. Fungsi potensial global dalam permainan strategis ini dikonstruksi secara ekuivalen dengan fungsi objektif portofolio untuk menjamin bahwa setiap titik ekuilibrium merepresentasikan kombinasi aset yang optimal. Pendekatan ekonofisika ini dimanfaatkan untuk mengarahkan pencarian solusi ke area lanskap energi Hamiltonian yang menjanjikan probabilitas tinggi dalam menemukan titik minimum global yang sebenarnya. Konfigurasi aset yang berada dalam keadaan ekuilibrium strategis ini digunakan sebagai injeksi pengetahuan klasik guna melakukan inisialisasi awal pada sirkuit kuantum variasional. Inisialisasi yang terarah ini dirancang secara khusus untuk mencegah algoritma kuantum terjebak dalam masalah dataran tandus atau konvergensi lokal pada ruang Hilbert berdimensi tinggi.

Mekanisme komputasi untuk menelusuri titik ekuilibrium strategis tersebut didefinisikan secara prosedural melalui skema iteratif yang terangkum dalam Algoritma \\ref{alg:nash_sbr}. Algoritma pencarian ini mengadopsi mekanisme \\textit{Sequential Best Response} yang bekerja dengan mengevaluasi peningkatan fungsi potensial melalui pertukaran posisi tunggal antar kandidat aset yang tersedia. Pada setiap iterasi komputasi, algoritma melakukan inspeksi menyeluruh terhadap semua kemungkinan kombinasi pertukaran aset untuk menemukan langkah paling curam menuju maksimalisasi utilitas global sistem. Proses pertukaran sekuensial ini terus dilanjutkan tanpa henti hingga algoritma mencapai status \\textit{steady-state} di mana tidak ada lagi modifikasi tunggal yang mampu meningkatkan utilitas portofolio tersebut. Bitstring final yang diproduksi oleh prosedur klasik ini kemudian diserahkan sepenuhnya ke modul komputasi kuantum sebagai parameter awal bagi gerbang rotasi ansatz.
""",
    'Contents/3_Metodologi/Bab-3.5.tex': """
Proses penyelesaian operator Hamiltonian portofolio dieksekusi menggunakan kerangka kerja \\textit{Hardware-Efficient Variational Quantum Eigensolver} (HE-VQE) yang didesain khusus untuk beroperasi pada perangkat keras kuantum berderau. Arsitektur sirkuit ansatz dikonfigurasi dengan memanfaatkan gerbang rotasi tunggal serta gerbang keterbelitan linier guna meminimalkan kedalaman sirkuit sembari mempertahankan tingkat ekspresivitas model yang tinggi. Sebuah mekanisme adaptasi kedalaman sirkuit diaplikasikan secara dinamis selama fase pelatihan untuk menyeimbangkan antara peningkatan akurasi solusi dengan kerentanan sistem terhadap akumulasi kesalahan gerbang fisik. Peningkatan koefisien pinalti secara gradual melalui skema \\textit{Penalty Annealing} turut diintegrasikan agar penelusuran ruang keadaan kuantum dapat menembus hambatan lokal tanpa melanggar kendala kardinalitas. Kolaborasi struktural antara inisialisasi ekuilibrium Nash dan ekspansi lapisan sirkuit ini menjamin stabilitas konvergensi energi minimum secara efisien.

Alur instruksi komputasi kuantum variasional yang mencakup kalibrasi hiperparameter hingga evaluasi nilai ekspektasi energi dispesifikasikan secara menyeluruh pada Algoritma \\ref{alg:vqe_adaptive}. Algoritma hibrida ini menerima konfigurasi bitstring inisial untuk menyiapkan parameter rotasi ansatz awal sebelum memulai siklus optimasi stokastik berbasis \\textit{Simultaneous Perturbation Stochastic Approximation} (SPSA). Di dalam blok iterasi utama, algoritma secara reguler menghitung gradien fungsi energi menggunakan teknik perturbasi ganda untuk memperbarui vektor parameter sudut dengan tingkat komputasi yang efisien. Apabila konvergensi energi tidak tercapai pada batas iterasi tertentu, modul ekspansi sirkuit akan diaktifkan secara otomatis untuk menambah kedalaman ansatz beserta parameter rotasi tambahannya. Output pamungkas dari algoritma kuantum ini adalah probabilitas distribusi keadaan basis yang paling dominan untuk merepresentasikan alokasi aset final yang paling optimal.
""",
    'Contents/3_Metodologi/Bab-3.6.tex': """
Verifikasi empiris terhadap performa portofolio kuantum dijalankan melalui mekanisme simulasi \\textit{backtesting} kronologis yang mereplikasi eksekusi investasi riil secara langsung pada data pasar historis. Jendela observasi data digeser secara periodik seiring berjalannya waktu investasi untuk memastikan bahwa model kuantum selalu dilatih ulang menggunakan distribusi harga saham paling mutakhir. Pembaruan parameter secara berkelanjutan ini diimplementasikan untuk mengakomodasi dinamika perubahan struktur korelasi serta mengkalibrasi ulang bobot risiko finansial dalam lanskap energi Hamiltonian sistemik. Faktor biaya transaksi akibat perubahan konfigurasi aset antar periode investasi dimasukkan secara matematis ke dalam fungsi evaluasi untuk memberikan estimasi keuntungan bersih yang realistis. Kalkulasi kumulatif dari metrik \\textit{Sharpe Ratio} dan persentase penarikan maksimum diaplikasikan guna mengukur efisiensi sistem secara komprehensif dibandingkan dengan strategi pembanding klasik.

Seluruh rangkaian prosedur validasi investasi dan perhitungan performa metrik evaluasi portofolio diformulasikan ke dalam struktur iteratif yang dijabarkan pada Algoritma \\ref{alg:backtesting_global}. Algoritma global ini mengorkestrasi eksekusi seluruh modul metodologi sebelumnya mulai dari akuisisi data awal, pemetaan matriks Ising, hingga optimasi kuantum variasional secara berurutan. Siklus iterasi yang terdapat pada algoritma utama ini merepresentasikan pergerakan waktu simulasi dari satu jendela pelatihan ke jendela pelatihan berikutnya dengan menggeser batas indeks data. Pencatatan riwayat keputusan alokasi aset beserta fluktuasi nilai energi sirkuit dieksekusi secara otomatis pada setiap akhir periode untuk keperluan visualisasi diagnostik komputasi akhir. Laporan metrik statistik yang dikembalikan oleh algoritma ini menjadi instrumen validasi utama untuk menilai keunggulan algoritma komputasi kuantum dalam mengoptimalkan portofolio investasi.
""",
    'Contents/3_Metodologi/Bab-3.7.tex': """
Penyelesaian masalah portofolio Markowitz secara tradisional menggunakan algoritma \\textit{Sequential Least Squares Programming} (SLSQP) diposisikan sebagai standar komparasi utama bagi keandalan model komputasi kuantum. Algoritma optimasi non-linear ini beroperasi dengan menyelesaikan serangkaian sub-masalah pemrograman kuadratik yang diaproksimasi melalui matriks Hessian serta vektor gradien dari fungsi utilitas finansial objektif. Pendekatan numerik deterministik ini dirancang untuk menangani batasan linier secara presisi, termasuk kendala total alokasi aset serta rentang batas bobot portofolio yang berkelanjutan secara kontinu. Meskipun metode klasik ini sangat efisien dalam menelusuri titik ekuilibrium lokal, algoritma ini cenderung memiliki keterbatasan teknis saat dihadapkan pada lanskap fungsi yang sangat kompleks. Integrasi metode klasik ini di dalam metodologi penelitian bertujuan untuk memberikan landasan pembuktian empiris mengenai percepatan pencarian konvergensi oleh algoritma berbasis kuantum.

Alur komputasi iteratif untuk optimasi bobot portofolio berkelanjutan dengan memanfaatkan matriks Hessian hampiran disajikan secara operasional pada Algoritma \\ref{alg:slsqp_optimizer}. Instruksi algoritma ini dimulai dengan penetapan bobot alokasi yang setara pada seluruh kandidat aset sebagai titik inisialisasi yang netral bagi pergerakan ruang solusi berkelanjutan. Pada setiap siklus komputasi, algoritma menghitung arah pencarian ideal berdasarkan gradien analitis dan melakukan pembaruan matriks menggunakan teknik kalibrasi kuasi-Newton secara sistematis dan efisien. Mekanisme pencarian garis atau \\textit{line search} diterapkan dalam blok iterasi untuk menentukan ukuran langkah optimal yang meminimalkan kerugian tanpa melanggar batas penyimpangan kendala matematis. Eksekusi program terus diulang hingga parameter bobot portofolio mencapai kriteria toleransi konvergensi yang ditetapkan guna menghasilkan vektor investasi kontinu terbaik sebagai perbandingan evaluasi.
""",
    'Contents/3_Metodologi/Bab-3.8.tex': """
Metode pencarian solusi eksak berbasis \\textit{brute force} diterapkan sebagai instrumen verifikasi absolut untuk menentukan kebenaran mutlak dari titik minimum global pada model energi Ising. Pendekatan komputasi konvensional ini mengevaluasi setiap kombinasi kandidat portofolio biner secara komprehensif guna mencatat nilai energi terendah yang berkorespondensi dengan alokasi investasi yang paling ideal. Pemanfaatan validasi eksak ini memberikan jaminan matematis yang tak terbantahkan bahwa solusi heuristik yang dihasilkan oleh sirkuit kuantum benar-benar mewakili konfigurasi aset terbaik yang ada. Kendati metode pencarian eksak ini tidak dapat diskalakan pada sistem dengan jumlah aset yang sangat besar, penggunaannya pada skala komputasi kecil tetap bernilai krusial. Hasil energi absolut yang ditemukan oleh metodologi validasi komprehensif ini menjadi rujukan final untuk menganalisis akurasi algoritma variasional kuantum secara objektif.

Prosedur penelusuran solusi mutlak melalui perhitungan fungsi biaya Hamiltonian pada seluruh elemen ruang keadaan biner diformalkan ke dalam kerangka Algoritma \\ref{alg:brute_force}. Algoritma komputasi eksak ini menerima parameter bias linier dan parameter kopling kuadratik untuk mengeksekusi perhitungan utilitas energi secara langsung pada setiap iterasi kombinasi aset. Modul pembangkit kombinasi yang tertanam di dalam algoritma memastikan bahwa hanya varian bitstring yang mematuhi kendala jumlah kardinalitas yang akan diuji dan diproses lebih lanjut. Mekanisme pencatatan nilai minimum dijalankan dengan memperbarui variabel energi terbaik setiap kali algoritma menemukan konfigurasi aset dengan ukuran energi yang lebih rendah secara numerik. Hasil keluaran berupa bitstring optimal dan energi terendah mutlak dari prosedur eksak ini dicatat secara permanen untuk memvalidasi tingkat akurasi konvergensi model hibrida kuantum.
"""
}

for filepath, new_text in files.items():
    with open(filepath, 'r') as f:
        content = f.read()
    
    # The text we want to replace is always between \section{...} and \begin{figure} or \begin{algorithm} or \begin{equation} (wait, Bab 3.2 has equation)
    # Actually, we can use regex to match everything between \section{...} and \begin{...}
    # But wait, Bab 3.2 has an equation in the text. My new text for 3.2 removed the equation!
    # Ah, the user said "fokus saja pada diagram alir dari algoritma-algoritma yang sudah ada". So if I remove the equation, is it fine? Yes, the user wants it to just introduce the algorithm.
    # Let's replace everything between \section{...} and the first \begin{figure} or \begin{algorithm}.
    
    # Find the section tag
    match_section = re.search(r'\\section\{[^}]+\}', content)
    if not match_section:
        continue
    
    start_idx = match_section.end()
    
    # Find the first \begin{figure} or \begin{algorithm}
    match_env = re.search(r'\\begin\{(figure|algorithm)\}', content[start_idx:])
    if not match_env:
        continue
        
    end_idx = start_idx + match_env.start()
    
    new_content = content[:start_idx] + "\n" + new_text.strip() + "\n\n" + content[end_idx:]
    
    with open(filepath, 'w') as f:
        f.write(new_content)

print("Rewriting completed.")
